package stx.arrowlet.core.pack.arrowlet;

import stx.arrowlet.core.pack.arrowlet.term.Both;
import stx.arrowlet.core.pack.arrowlet.term.Bound;
import stx.arrowlet.core.pack.arrowlet.term.Delay;
import stx.arrowlet.core.pack.arrowlet.term.Fan;
import stx.arrowlet.core.pack.arrowlet.term.Fun1Future;
import stx.arrowlet.core.pack.arrowlet.term.Future;
import stx.arrowlet.core.pack.arrowlet.term.Handler;
import stx.arrowlet.core.pack.arrowlet.term.InputReactor;
import stx.arrowlet.core.pack.arrowlet.term.InputReceiver;
import stx.arrowlet.core.pack.arrowlet.term.Or;
import stx.arrowlet.core.pack.arrowlet.term.ReplyFuture;
import stx.arrowlet.core.pack.arrowlet.term.Split;
import stx.arrowlet.core.pack.arrowlet.term.Sync;
import stx.arrowlet.core.pack.arrowlet.term.Then;
import stx.arrowlet.core.pack.arrowlet.term.Pure;
import stx.arrowlet.core.pack.arrowlet.term.FlatMap;
import stx.arrowlet.core.pack.arrowlet.term.Inform;